apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-application-deployment
  template:
    metadata:
      labels:
        app: web-application
    spec:
      containers:
      - name: web-application
        image: staplesadvembed.azurecr.io/staplesadvembed
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: web-application-svc
spec:
  selector:
    app: web-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer